theme: minima
title: Tyler Ebel
description: memory dump

author:
  name: ebel
  email: tebel@tylerebel.com

social_links:
  twitter: https://twitter.com/tylerebel9
  github: https://github.com/ebe;
  linkedin: https://www.linkedin.com/in/tylerebel

