theme: minima
title: Tyler Ebel
description: memory dump

author:
  name: ebel
  email: tebel@tylerebel.com


twitter_username: tylerebel9
github_username: ebel
linkedin_username: tylerebel

baseurl: ""