name: Build and deploy Zola site to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive  # Ensures all submodules are checked out

      - name: Install Zola
        uses: taiki-e/install-action@v2
        with:
          tool: zola@0.17.2

      - name: Build the site
        run: zola build

      - name: Verify the existence of the public directory
        run: |
          echo "Checking if 'public' directory exists..."
          if [ -d "public" ]; then
            echo "'public' directory exists."
          else
            echo "'public' directory does not exist."
            exit 1
          fi

      - name: List files in the public directory
        run: ls -la public

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public